name: Lambda Layer - Python Requirements

# Installed Software
# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

# Python Layer Paths
# https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path

# Controls when the workflow will run
on:
  push:
    branches:
      - master
    paths:
      - "layer/**"
  pull_request:
    branches:
      - master
    paths:
      - "layer/**"

defaults:
  run:
    shell: bash

jobs:

  deploynonprod:
    name: Deploy to NonProd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.NONPROD_DEPLOYMENT_ROLE }}
          role-session-name: deploylambda
          role-duration-seconds: 900

      - name: Build and Create Layer
        uses: stephenbawks/aws-lambda-layer@v0.0.17
        with:
            layer-name: my-awesome-layer-name
            layer-directory: layer
            runtime: python
            bucketname: my-s3-bucket-name-goes-here
            prefix-folder-path: beta
            principal: "*"